[package]
name = "winit_20240517"
version = "0.1.0"
edition = "2021"

[dependencies]
pixels = "0.13.0"
winit = { version = "0.30.0", features = ["rwh_06", "rwh_05", "rwh_04", "x11"], default-features = false }
